backend:
  name: git-gateway
  repo: mnogueron/gatsby-bml78
  branch: master

local_backend: true

media_folder: static/assets
public_folder: /assets

title: &TITLE { label: 'Nom du document', name: 'title', widget: 'string' }
card_title: &CARD_TITLE { label: 'Titre de carte', name: 'cardTitle', widget: 'string', required: false }
publish_date: &PUBLISH_DATE { label: 'Date de publication', name: 'date', widget: 'datetime' }
heading:
  &HEADING { label: 'Titre principal', name: heading, widget: text, required: false }
subheading:
  &SUBHEADING {
    label: 'Sous-titre',
    name: subheading,
    widget: string,
    required: false,
  }
body: &BODY { label: 'Contenu', name: 'body', widget: 'markdown' }
template_base:
  &TEMPLATE_BASE {
    label: 'Template Key',
    name: 'templateKey',
    widget: 'hidden',
  }

seo: &SEO
  label: 'SEO'
  name: 'seo'
  widget: object
  collapsed: true
  required: false
  fields:
    - { label: 'Titre', name: 'title', widget: 'string', required: false }
    - {
        label: 'Description',
        name: 'description',
        widget: 'string',
        required: false,
      }
    - { label: Image, name: image, widget: image, required: false }

content_page: &CONTENT_PAGE
  - <<: *TEMPLATE_BASE
    default: 'content-page'
  - <<: *TITLE
  - <<: *HEADING
  - <<: *SUBHEADING
  - <<: *BODY
  - <<: *SEO

result_page: &RESULT_PAGE
  - <<: *TEMPLATE_BASE
    default: 'result-page'
  - <<: *TITLE
    default: 'interclub-equipe-'
  - <<: *CARD_TITLE
  - <<: *HEADING
  - <<: *SUBHEADING
  - <<: *PUBLISH_DATE
  - {
      label: Category,
      name: category,
      widget: relation,
      collection: 'result-sections',
      search_fields: ['heading'],
      value_field: 'title',
      display_fields: ['{{heading}} - {{subheading}}'],
    }
  - <<: *BODY
  - {
      label: 'Featured Image',
      name: 'featuredimage',
      widget: object,
      collapsed: true,
      fields:
        [
          {
            label: Image,
            name: image,
            widget: image,
            default: '/assets/shuttle.jpg',
          },
          { label: Alt, name: alt, widget: string, required: false },
        ],
    }
  - <<: *SEO

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Accueil'
        name: 'index'
        fields:
          - <<: *TEMPLATE_BASE
            default: 'index-page'
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Image de fond, name: headerImage, widget: image }
          - { label: Heading, name: heading, widget: text }
          - { label: Subheading, name: subheading, widget: text }
          - { label: "Le club", name: body, widget: markdown }
          - {
              label: Bannière,
              name: banner,
              widget: object,
              required: false,
              fields:
                [
                  {label: Message, name: text, widget: text, required: false},
                  {label: Importance, name: level, widget: select, options: [info, warning], required: false},
                  {label: Cacher la bannière ?, name: hide, widget: boolean, require: false},
                ]
          }
          # - { label: "Body", name: "body", widget: "markdown" }
          # - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          # - {label: Description, name: description, widget: string}
          # - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          # - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          # - {
          #     label: "About",
          #     name: "about",
          #     widget: object,
          #     fields:
          #       [
          #         { label: Heading, name: heading, widget: string },
          #         { label: Description, name: description, widget: text },
          #         {
          #           label: Image,
          #           name: image,
          #           widget: object,
          #           fields:
          #             [
          #               { label: Image, name: image, widget: image },
          #               { label: Alt, name: alt, widget: string },
          #             ],
          #         },
          #         {
          #           label: Button,
          #           name: button,
          #           widget: object,
          #           fields:
          #             [
          #               { label: Label, name: label, widget: string },
          #               { label: URL, name: url, widget: string },
          #             ],
          #         },
          #       ],
          #   }
          - <<: *SEO
      - file: 'src/pages/articles/index.md'
        label: 'Actualités'
        name: 'articles-index'
        fields:
          - <<: *TEMPLATE_BASE
            default: 'articles-page'
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
      - file: 'src/pages/results/index.md'
        label: 'Tous les résulats'
        name: 'all-results-index'
        fields:
          - <<: *TEMPLATE_BASE
            default: 'all-results-page'
          - <<: *TITLE
          - <<: *HEADING
          - <<: *SUBHEADING
          - <<: *SEO
      # - file: "src/pages/about/index.md"
      #   label: "À propos"
      #   name: "about"
      #   fields:
      #     - {
      #         label: "Template Key",
      #         name: "templateKey",
      #         widget: "hidden",
      #         default: "about-page",
      #       }
      #     - { label: "Title", name: "title", widget: "string" }
      #     - { label: Heading, name: heading, widget: string }
      #     - { label: Subheading, name: subheading, widget: string }
      #     - { label: "Body", name: "body", widget: "markdown" }
      #     - {
      #         label: Team,
      #         label_singular: Member,
      #         name: team,
      #         widget: list,
      #         fields:
      #           [
      #             { label: Name, name: name, widget: string },
      #             { label: Title, name: title, widget: string },
      #             { label: Image, name: image, widget: image },
      #           ],
      #       }

      - file: 'src/pages/contact/index.md'
        label: 'Contact'
        name: 'contact'
        fields:
          - <<: *TEMPLATE_BASE
            default: 'contact-page'
          - <<: *TITLE
          - <<: *HEADING
          - <<: *SUBHEADING
          - <<: *BODY
          - {
              label: 'Formulaire de contact',
              name: contactform,
              widget: object,
              fields:
                [
                  { label: 'Titre', name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          #- {
          #    label: Office,
          #    name: office,
          #    widget: object,
          #    fields:
          #      [
          #        { label: Tagline, name: tagline, widget: string },
          #        { label: Location, name: location, widget: string },
          #        { label: Address, name: address, widget: markdown },
          #        { label: Phone, name: phone, widget: markdown },
          #        { label: Image, name: image, widget: image },
          #      ],
          #  }
          - <<: *SEO

  - name: 'informations'
    label: 'Infos Pratiques'
    files:
      - file: 'src/pages/infos-pratiques/inscription.md'
        label: 'Inscription'
        name: 'inscription'
        fields: *CONTENT_PAGE
      - file: 'src/pages/infos-pratiques/avantages.md'
        label: 'Avantages'
        name: 'avantages'
        fields: *CONTENT_PAGE
      - file: 'src/pages/infos-pratiques/entrainements.md'
        label: 'Entraînements'
        name: 'entrainements'
        fields: *CONTENT_PAGE
      - file: 'src/pages/infos-pratiques/sections.md'
        label: 'Nos Sections'
        name: 'sections'
        fields: *CONTENT_PAGE
      - file: 'src/pages/infos-pratiques/acces-horaires.md'
        label: 'Accès / Horaires'
        name: 'acces-horaires'
        fields: *CONTENT_PAGE
      - file: 'src/pages/infos-pratiques/calendrier.md'
        label: 'Calendrier'
        name: 'calendrier'
        fields: *CONTENT_PAGE
      - file: 'src/pages/infos-pratiques/bureau.md'
        label: 'Le Bureau'
        name: 'bureau'
        fields:
          - <<: *TEMPLATE_BASE
            default: 'board-chart-page'
          - <<: *TITLE
          - <<: *HEADING
          - <<: *SUBHEADING
          - <<: *BODY
          - label: Président
            name: president
            widget: object
            fields:
              - { label: Nom, name: name, widget: string }
              - { label: Photo, name: picture, widget: image, required: false }
          - label: Trésorier
            name: treasurer
            widget: object
            fields:
              - { label: Nom, name: name, widget: string }
              - { label: Photo, name: picture, widget: image, required: false }
          - label: Secrétaire Général
            name: secretary
            widget: object
            fields:
              - { label: Nom, name: name, widget: string }
              - { label: Photo, name: picture, widget: image, required: false }
          - label: Membres
            label_singular: Membre
            name: board
            widget: list
            fields:
              - { label: Nom, name: name, widget: string }
              - { label: Titre, name: title, widget: string }
              - { label: Photo, name: picture, widget: image, required: false }

          - <<: *SEO

  - name: 'articles'
    label: 'Articles'
    folder: 'src/pages/articles'
    filter: { field: 'templateKey', value: 'article-page' }
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '[{{day}}-{{month}}-{{year}}] {{title}}'
    fields:
      - <<: *TEMPLATE_BASE
        default: 'article-page'
      - <<: *TITLE
      - <<: *CARD_TITLE
      - <<: *HEADING
      - <<: *PUBLISH_DATE
      # - {label: "Description", name: "description", widget: "text"}
      # - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {
          label: 'Featured Image',
          name: 'featuredimage',
          widget: object,
          fields:
            [
              { label: Image, name: image, widget: image },
              { label: Alt, name: alt, widget: string },
              { label: Caché, name: hidden, widget: boolean, required: false },
            ],
        }
      - <<: *BODY
      - <<: *SEO
      # - {label: "Tags", name: "tags", widget: "list"}
  - name: 'results'
    label: 'Résultats'
    label_singular: 'Résultat'
    folder: 'src/pages/results'
    filter: { field: 'templateKey', value: 'result-page' }
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}'
    summary: '[{{day}}-{{month}}-{{year}}] {{heading}}'
    view_filters:
      - label: "Saison 2022 - 2023"
        field: heading
        pattern: 'Saison 22-23'
      - label: "Saison 2021 - 2022"
        field: heading
        pattern: 'Saison 21-22'
      - label: "Equipe 1"
        field: category
        pattern: 'equipe-1'
      - label: "Equipe 2"
        field: category
        pattern: 'equipe-2'
      - label: "Equipe 3"
        field: category
        pattern: 'equipe-3'
      - label: "Equipe 4"
        field: category
        pattern: 'equipe-4'
      - label: "Equipe 5"
        field: category
        pattern: 'equipe-5'
      - label: "Equipe 6"
        field: category
        pattern: 'equipe-6'
    fields: *RESULT_PAGE

  - name: 'result-sections'
    label: 'Catégories de résultat'
    label_singular: 'Catégorie de résultat'
    folder: 'src/pages/results'
    filter: { field: 'templateKey', value: 'results-page' }
    create: true
    slug: '{{fields.title}}'
    summary: '[{{fields.subheading}}] {{fields.heading}}'
    fields:
      - <<: *TEMPLATE_BASE
        default: 'results-page'
      - <<: *TITLE
      - <<: *HEADING
      - <<: *SUBHEADING
      - <<: *SEO
  - name: 'menus'
    label: 'Menus'
    files:
      - file: 'src/pages/menus/infos-pratiques.md'
        label: 'Menu - Infos pratiques'
        name: 'infos-pratiques'
        fields:
          - label: 'Menu key'
            name: 'menuKey'
            widget: 'hidden'
            default: 'infos-pratiques'
          - label: Sections
            label_singular: Section
            name: items
            widget: list
            summary: 'Titre de la section : {{fields.title}} - Page associée : {{fields.url}}'
            fields:
              - label: Titre
                name: title
                widget: string
              - label: Page
                name: url
                widget: relation
                collection: 'informations'
                search_fields: ['title']
                value_field: '/infos-pratiques/{{slug}}'
                display_fields: ['title']
      - file: 'src/pages/menus/resultats.md'
        label: 'Menu - Résultats'
        name: 'resultats'
        fields:
          - {
              label: 'Menu Key',
              name: 'menuKey',
              widget: 'hidden',
              default: 'resultats',
            }
          - label: Sections
            label_singular: Section
            name: items
            widget: list
            summary: 'Titre de la section : {{fields.title}} - Page associée : {{fields.url}}'
            fields:
              - label: Titre
                name: title
                widget: string
              - label: Page
                name: url
                widget: relation
                required: false
                collection: 'result-sections'
                search_fields: ['heading']
                value_field: '/results/{{slug}}'
                display_fields: ['{{heading}} - {{subheading}}']
              - label: Saisons
                label_singular: Saison
                name: items
                required: false
                widget: list
                summary: 'Saison : {{fields.title}} - Page associée : {{fields.url}}'
                fields:
                  - label: Titre
                    name: title
                    widget: string
                  - label: Page
                    name: url
                    widget: relation
                    collection: 'result-sections'
                    search_fields: ['heading']
                    value_field: '/results/{{slug}}'
                    display_fields: ['{{heading}} - {{subheading}}']
