backend:
  name: github
  repo: mnogueron/gatsby-bml78
  branch: master

local_backend: true

media_folder: static/img
public_folder: /img

content_page: &CONTENT_PAGE
  - {
    label: "Template Key",
    name: "templateKey",
    widget: "hidden",
    default: "content-page",
  }
  - { label: "Title", name: "title", widget: "string" }
  - {
    label: Category,
    name: category,
    widget: relation,
    collection: "result-sections",
    search_fields: [ "heading" ],
    value_field: "title",
    display_fields: [ "heading" ],
  }
  - { label: Heading, name: heading, widget: string, required: false }
  - { label: Subheading, name: subheading, widget: string, required: false }
  - { label: "Body", name: "body", widget: "markdown" }
  - {
    label: "Featured Image",
    name: "featuredimage",
    widget: object,
    collapsed: true,
    fields:
      [
        { label: Image, name: image, widget: image, default: "/img/shuttle.jpg", },
        { label: Alt, name: alt, widget: string, required: false },
      ],
  }

header_fields: &HEADER_FIELDS
  - {
    label: "Template Key",
    name: "templateKey",
    widget: "hidden",
    default: "results-page",
  }
  - { label: "Title", name: "title", widget: "string" }
  - { label: Heading, name: heading, widget: string, required: false }
  - { label: Subheading, name: subheading, widget: string, required: false }

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Accueil"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          # - { label: "Body", name: "body", widget: "markdown" }
          # - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          # - {label: Description, name: description, widget: string}
          # - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          # - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {
              label: "About",
              name: "about",
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image,
                    name: image,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Button,
                    name: button,
                    widget: object,
                    fields:
                      [
                        { label: Label, name: label, widget: string },
                        { label: URL, name: url, widget: string },
                      ],
                  },
                ],
            }
      - file: "src/pages/articles/index.md"
        label: "Actualités"
        name: "articles-index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "articles-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
      - file: "src/pages/results/index.md"
        label: "Tous les résulats"
        name: "all-results-index"
        fields:
          - {
            label: "Template Key",
            name: "templateKey",
            widget: "hidden",
            default: "all-results-page",
          }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Heading, name: heading, widget: string, required: false }
          - { label: Subheading, name: subheading, widget: string, required: false }
      - file: "src/pages/about/index.md"
        label: "À propos"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: Team,
              label_singular: Member,
              name: team,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Title, name: title, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }

      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: ContactForm,
              name: contactform,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Office,
              name: office,
              widget: object,
              fields:
                [
                  { label: Tagline, name: tagline, widget: string },
                  { label: Location, name: location, widget: string },
                  { label: Address, name: address, widget: markdown },
                  { label: Phone, name: phone, widget: markdown },
                  { label: Image, name: image, widget: image },
                ],
            }

  - name: "informations"
    label: "Infos Pratiques"
    files:
      - file: "src/pages/infos-pratiques/inscription.md"
        label: "Inscription"
        name: "inscription"
        fields: *CONTENT_PAGE
      - file: "src/pages/infos-pratiques/avantages.md"
        label: "Avantages"
        name: "avantages"
        fields: *CONTENT_PAGE
      - file: "src/pages/infos-pratiques/entrainements.md"
        label: "Entraînements"
        name: "entrainements"
        fields: *CONTENT_PAGE
      - file: "src/pages/infos-pratiques/sections.md"
        label: "Nos Sections"
        name: "sections"
        fields: *CONTENT_PAGE
      - file: "src/pages/infos-pratiques/calendrier.md"
        label: "Calendrier"
        name: "calendrier"
        fields: *CONTENT_PAGE

  - name: "articles"
    label: "Articles"
    folder: "src/pages/articles"
    filter: {field: "templateKey", value: "article-page"}
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} {{year}}-{{month}}-{{day}} {{fields.featured}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "article-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured", name: "featured", widget: boolean }
      # - {label: "Description", name: "description", widget: "text"}
      # - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {
          label: "Featured Image",
          name: "featuredimage",
          widget: object,
          fields:
            [
              { label: Image, name: image, widget: image },
              { label: Alt, name: alt, widget: string },
            ],
        }
      - { label: Location, name: location, widget: string }
      - { label: "Body", name: "body", widget: "markdown" }
      # - {label: "Tags", name: "tags", widget: "list"}
  - name: "results"
    label: "Résultats"
    label_singular: "Résultat"
    folder: "src/pages/results"
    filter: { field: "templateKey", value: "result-page" }
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} {{year}}-{{month}}-{{day}} {{fields.featured}}"
    fields: *CONTENT_PAGE

  - name: "result-sections"
    label: "Catégories de résultat"
    label_singular: "Catégorie de résultat"
    folder: "src/pages/results"
    filter: { field: "templateKey", value: "results-page" }
    create: true
    slug: "{{fields.title}}"
    summary: "{{title}}"
    fields: *HEADER_FIELDS
